# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Report',
        ),
    ]
