# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0002_auto_20171008_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='writer',
        ),
    ]
