# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0006_auto_20171013_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
