# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0008_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(verbose_name='이름'),
        ),
    ]
