# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0010_auto_20171015_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='200글자까지 가능합니다', max_length=200),
        ),
    ]
