# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0011_auto_20171015_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_password',
            field=models.CharField(default='0000', help_text='글을 수정하거나 지울 때 사용할 비밀번호를 적어주세요', max_length=100, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
