# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0012_auto_20171015_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bamboo.Category'),
        ),
    ]
