# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0013_auto_20171015_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bamboo.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_password',
            field=models.CharField(default='', help_text='글을 수정하거나 지울 때 사용할 비밀번호를 적어주세요', max_length=100, verbose_name='password'),
        ),
    ]
